import whyTitle from '../images/whyTitle.png'
import FollowKelly from './FollowKelly'

const KellysWhy = () => {
    return(
        
        <div id="why-container" className='card'>
            <img src={whyTitle} id='why-title' alt="My Ride 
            across the united state"/>
            <iframe title="What is ALS? Video"id="why-vid" scrolling="no" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen allow="autoplay; fullscreen" src="https://w3.cdn.anvato.net/player/prod/v3/anvload.html?key=eyJtIjoiY2JzIiwidiI6IjU3MDgwNjkiLCJhbnZhY2siOiI1VkQ2RXlkNmRqZXdiQ21Od0JGbnNKajE3WUF2R1J3bCIsInNoYXJlTGluayI6Imh0dHBzOi8vY2JzbG9jLmFsLzNxZ25McGUiLCJwbHVnaW5zIjp7ImNvbXNjb3JlIjp7ImNsaWVudElkIjoiMzAwMDAyMyIsImMzIjoiZ29vZGRheXNhY3JhbWVudG8uY2JzbG9jYWwuY29tIn0sImRmcCI6eyJjbGllbnRTaWRlIjp7ImFkVGFnVXJsIjoiaHR0cDovL3B1YmFkcy5nLmRvdWJsZWNsaWNrLm5ldC9nYW1wYWQvYWRzP3N6PTJ4MiZpdT0vNDEyOC9jdy5nZGF5JmNpdV9zenMmaW1wbD1zJmdkZnBfcmVxPTEmZW52PXZwJm91dHB1dD14bWxfdmFzdDImdW52aWV3ZWRfcG9zaXRpb25fc3RhcnQ9MSZ1cmw9W3JlZmVycmVyX3VybF0mZGVzY3JpcHRpb25fdXJsPVtkZXNjcmlwdGlvbl91cmxdJmNvcnJlbGF0b3I9W3RpbWVzdGFtcF0iLCJrZXlWYWx1ZXMiOnsiY2F0ZWdvcmllcyI6IltbQ0FURUdPUklFU11dIiwicHJvZ3JhbSI6IltbUFJPR1JBTV9OQU1FXV0iLCJzaXRlU2VjdGlvbiI6ImZlYXR1cmVkIn19LCJsaWJyYXJ5UmVxdWVzdGVkIjp0cnVlfSwiaGVhcnRiZWF0QmV0YSI6eyJhY2NvdW50IjoiY2JzbG9jYWwtZ2xvYmFsLXVuaWZpZWQiLCJwdWJsaXNoZXJJZCI6ImNic2xvY2FsIiwiam9iSWQiOiJzY192YSIsIm1hcmtldGluZ0Nsb3VkSWQiOiI4MjNCQTAzMzU1Njc0OTdGN0YwMDAxMDFAQWRvYmVPcmciLCJ0cmFja2luZ1NlcnZlciI6ImNic2RpZ2l0YWxtZWRpYS5oYi5vbXRyZGMubmV0IiwiY3VzdG9tVHJhY2tpbmdTZXJ2ZXIiOiJjYnNkaWdpdGFsbWVkaWEuZDEuc2Mub210cmRjLm5ldCIsImNoYXB0ZXJUcmFja2luZyI6ZmFsc2UsInZlcnNpb24iOiIxLjUiLCJwYXJlbnRQYWdlVVJMIjoiaHR0cHM6Ly9nb29kZGF5c2FjcmFtZW50by5jYnNsb2NhbC5jb20vMjAyMS8wNi8yMS9sb2RpLWN5Y2xpbmctY3Jvc3MtY291bnRyeS1iaWtlLXJpZGUtY2F1c2VzLyIsInBhcmVudFRpdGxlIjoi4oCYSXTigJlzIEdvaW5nIFRvIFRha2UgQSBCaXTigJk6IExvZGkgQ3ljbGlzdCBQbGFubmluZyBDcm9zcy1Db3VudHJ5IEJpa2UgUmlkZSBGb3IgR29vZCBDYXVzZXMg4oCTIEdvb2QgRGF5IFNhY3JhbWVudG8iLCJwSW5zdGFuY2UiOiJwMCIsInByb2ZpbGUiOiJjYnMiLCJjdXN0b21UcmFja2luZ1NlcnZlclNlY3VyZSI6ImNic2RpZ2l0YWxtZWRpYS5kMS5zYy5vbXRyZGMubmV0In0sImhlYWx0aEFuYWx5dGljcyI6e319LCJodG1sNSI6dHJ1ZSwidG9rZW4iOiJkZWZhdWx0In0%3D"  width ="640" height="360"></iframe>
            <i><h5 id='why'>Why?</h5></i>
            <p className='kellys-why'>To serve.  To build community.  To help because I can. I ride because I am able.  I work in the animal health field for an incredible company, Boehringer Ingelheim.  My passion is animals and helping others.  I am lucky to have a job that is not “work” because it offers the opportunity to do both of these things.  Some veterinarians are affected by depression and suicide.  Family, friends, neighbors and people I will never meet affected by the devastating diagnosis and affects of cancer.</p> 
            <p className='kellys-why'> This ride offers the same opportunity to help those I love—My wife, Shelley, my friend JD and one of my best friend’s mothers, growing up. Finally, with every pedal stroke I am able to help individuals living with the destructive neuromuscular effects of amyotrophic lateral sclerosis, when they are not able to help themselves.</p>
            <p className='kellys-why'>This ride is a ride for life.  A “Ride for 5” causes that can save a life, extend a life, change a life.  Luckily, mine will undoubtedly be one of those.</p>
            <h3 id="good-day-title">Good Day Sacramento</h3>
            <iframe id="good-day-vid" scrolling="no" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen allow="autoplay; fullscreen" src="https://w3.cdn.anvato.net/player/prod/v3/anvload.html?key=eyJtIjoiY2JzIiwidiI6IjU3MDU0MjUiLCJhbnZhY2siOiI1VkQ2RXlkNmRqZXdiQ21Od0JGbnNKajE3WUF2R1J3bCIsInNoYXJlTGluayI6Imh0dHBzOi8vY2JzbG9jLmFsLzN3S01JZjEiLCJwbHVnaW5zIjp7ImNvbXNjb3JlIjp7ImNsaWVudElkIjoiMzAwMDAyMyIsImMzIjoiZ29vZGRheXNhY3JhbWVudG8uY2JzbG9jYWwuY29tIn0sImRmcCI6eyJjbGllbnRTaWRlIjp7ImFkVGFnVXJsIjoiaHR0cDovL3B1YmFkcy5nLmRvdWJsZWNsaWNrLm5ldC9nYW1wYWQvYWRzP3N6PTJ4MiZpdT0vNDEyOC9jdy5nZGF5JmNpdV9zenMmaW1wbD1zJmdkZnBfcmVxPTEmZW52PXZwJm91dHB1dD14bWxfdmFzdDImdW52aWV3ZWRfcG9zaXRpb25fc3RhcnQ9MSZ1cmw9W3JlZmVycmVyX3VybF0mZGVzY3JpcHRpb25fdXJsPVtkZXNjcmlwdGlvbl91cmxdJmNvcnJlbGF0b3I9W3RpbWVzdGFtcF0iLCJrZXlWYWx1ZXMiOnsiY2F0ZWdvcmllcyI6IltbQ0FURUdPUklFU11dIiwicHJvZ3JhbSI6IltbUFJPR1JBTV9OQU1FXV0iLCJzaXRlU2VjdGlvbiI6InZpZGVvLWV4cGVyaWVuY2UifX0sImxpYnJhcnlSZXF1ZXN0ZWQiOnRydWV9LCJoZWFydGJlYXRCZXRhIjp7ImFjY291bnQiOiJjYnNsb2NhbC1nbG9iYWwtdW5pZmllZCIsInB1Ymxpc2hlcklkIjoiY2JzbG9jYWwiLCJqb2JJZCI6InNjX3ZhIiwibWFya2V0aW5nQ2xvdWRJZCI6IjgyM0JBMDMzNTU2NzQ5N0Y3RjAwMDEwMUBBZG9iZU9yZyIsInRyYWNraW5nU2VydmVyIjoiY2JzZGlnaXRhbG1lZGlhLmhiLm9tdHJkYy5uZXQiLCJjdXN0b21UcmFja2luZ1NlcnZlciI6ImNic2RpZ2l0YWxtZWRpYS5kMS5zYy5vbXRyZGMubmV0IiwiY2hhcHRlclRyYWNraW5nIjpmYWxzZSwidmVyc2lvbiI6IjEuNSIsImN1c3RvbU1ldGFkYXRhIjp7InZpZGVvIjp7ImNic19tYXJrZXQiOiJnb29kZGF5c2FjcmFtZW50by5jYnNsb2NhbC5jb20iLCJjYnNfcGxhdGZvcm0iOiJkZXNrdG9wIn19LCJwYXJlbnRQYWdlVVJMIjoiaHR0cHM6Ly9nb29kZGF5c2FjcmFtZW50by5jYnNsb2NhbC5jb20vdmlkZW8vNTcwNTQyNS1yaWRlLWZvci1maXZlLyIsInBhcmVudFRpdGxlIjoiUmlkZSBGb3IgRml2ZSIsInBJbnN0YW5jZSI6InAwIiwicHJvZmlsZSI6ImNicyIsImN1c3RvbVRyYWNraW5nU2VydmVyU2VjdXJlIjoiY2JzZGlnaXRhbG1lZGlhLmQxLnNjLm9tdHJkYy5uZXQifSwiaGVhbHRoQW5hbHl0aWNzIjp7fX0sImh0bWw1Ijp0cnVlLCJ0b2tlbiI6ImRlZmF1bHQifQ%3D%3D"  width ="640" height="360"></iframe>
            <h4 id="news-article-subtitle">Lodian plans to ride bike across country for wife, charities</h4>
            <h4 id="news-article-title">Wes Bowers, Lodi News-Sentinel, Calif.</h4>
            <p id="article-date">June 19, 2021</p>
            <p className='kellys-why'>A Lodi native is planning to ride a bicycle more than 2,500 miles later this year in the name of five different charities. And he'll have a former mentor and teacher alongside him every pedal of the way.</p>
            <p>Kelly O'Keefe plans to ride from San Francisco to Savannah, Ga., on July 31, with the goal of making it to the East Coast by the end of September.</p>
            <p>"We started talking about it last fall," he said. "My wife thought it was nuts, but she's kind of used to this type of stuff I do. We just kind of talked about it and then she was diagnosed with ovarian cancer at the end of February. I had already started thinking about (riding for) Not One More Vet, because my company is really big into helping that cause out."</p>
            <p>O'Keefe will be riding not only for his wife Shelley, but Not One More Vet, World Vets, the ALS Foundation and the V Foundation for Cancer Research. His ride for the V Foundation stems from a veterinarian friend who lost his battle with pancreatic cancer, and his ride for the ALS Foundation is based on his admiration for childhood idol George Brett, the former Kansas City Royals star who raises money for research in the Kansas City area.</p>
            <p>The distance between San Francisco and Savannah is over 3,600 miles to ride and takes about 40 hours to drive.</p>
            <p>O'Keefe plans to ride across the Golden Gate Bridge both ways, then take a ferry to Vallejo and make his way through Davis, Sacramento and Folsom before heading south of Lake Tahoe toward Carson City, Nev. He'll ride Highway 50 up to Interstate 80 near Fernley, Nev., then head east through Utah, Colorado, Kansas, and Missouri, among other states along the way.</p>
            <p>A group of Lodi residents will join him for one day of the ride here in California, but for the entire length of the trip, he'll be joined by his high school English teacher Mike Kennedy.</p>
            <p>"I enjoyed working with Kelly years ago, and he called me up with an opportunity to work with him again for a very good cause," Kennedy said. "I said yes. I have a lot of confidence in Kelly, I have a lot of confidence in what he's wanting to accomplish. Continuing education is really important, and I've been really grateful that former students have come back into my life in a variety of ways and have educated and encouraged me in things that are going on. "Kennedy won't be riding a bicycle though. He'll be driving the route with O'Keefe, loaded up with supplies he might need along the way.</p>
            <p>He said the journey coincides with a trip inspired by the books "Travels With Charlie" by John Steinbeck and "Blue Highways" by William Least Heat-Moon.</p>
            <p>"Those are two trips I'm very aware of and have thought of replicating myself, so this seems like a first half of my expedition, which would then be to get back here," he said. "The opportunity to work with a former student who has an admirable goal that is community based and community affirming ... that affirmation and community is kind of what caused me to say yes. This is about helping someone achieve a goal and a dream. "Once they reach Savannah, O'Keefe plans to fly home to meet his family, and Kennedy will make the return trip by automobile.</p>
            <p>O'Keefe said he's completed the Death Ride, a 128-mile bicycle trek in the Sierra Nevada, as well as a marathon for The Arthritis Foundation.</p>
            <p className="news-aritcle">"I'll be a lot less nervous without Mike," he said of his cross-country challenge. "I honestly could not do it without the support of everybody, but also not only the friendship, but the vehicle to be able to carry things."</p>
            <p className="news-aritcle">O'Keefe said he contacted Kennedy because he was trying to think of the best fit as a traveling companion for the trip, and added he chose to cycle rather than any other physical activity because he had got back into the sport recently, and when he told the staff at Lodi Cyclery about his plans, they offered support through sponsorships and supplies.</p>
            <p className="news-aritcle">A 1988 graduate of Lodi High, O'Keefe attended Delta College and Stanislaus State, graduating from the latter in 1994. He joined the Peace Corps in 1995, and has worked in sales since 2004.</p>
            <p className="news-aritcle">He met his Denver-born wife by chance at the Shannon Airport in Ireland in 2009. O'Keefe was living in Carson City at the time, and she was in Dallas, but they married in 2010 and moved to Lodi two years later. The couple have a 10-year-old daughter and an 8-year-old son.</p>
            <p className="news-aritcle">He said his wife has done amazingly well since her diagnosis, completing five of six chemotherapy treatments, Her final session will be just days before he leaves for the trek.</p>
            <p className="news-aritcle">"Each time she knows what to expect," he said. "She knows she's going to be hurting and she's going to be out of it, resting. Everyone says it's got to be rough on me because I have to take care of everything else, but I always just say I have the easy part. Because she's the one going through all the hard stuff. It's sort of parallel with the bike. I'm going to be doing some hard work, but these people with ALS or cancer or depression or suicidal thoughts ... that's the hard stuff."</p>
            <p className="news-aritcle lastP">O'Keefe will be setting up a GoFundMe this weekend, and plans to update friends, family and social media followers during his trip on Instagram @kellyridesfor5.</p>
            <FollowKelly/>
        </div>
    )
}

export default KellysWhy;